export const FEED_WS_DISCONNECT: 'FEED_WS_DISCONNECT' = 'FEED_WS_DISCONNECT';
export const FEED_WS_CONNECT: 'FEED_WS_CONNECT' = 'FEED_WS_CONNECT';
export const FEED_WS_CONNECTION_START: 'FEED_WS_CONNECTION_START' = 'FEED_WS_CONNECTION_START';
export const FEED_WS_CONNECTION_SUCCESS: 'FEED_WS_CONNECTION_SUCCESS' = 'FEED_WS_CONNECTION_SUCCESS';
export const FEED_WS_CONNECTION_ERROR: 'FEED_WS_CONNECTION_ERROR' = 'FEED_WS_CONNECTION_ERROR';
export const FEED_WS_CONNECTION_CLOSED: 'FEED_WS_CONNECTION_CLOSED' = 'FEED_WS_CONNECTION_CLOSED';
export const FEED_WS_GET_MESSAGE: 'FEED_WS_GET_MESSAGE' = 'FEED_WS_GET_MESSAGE';
export const FEED_WS_SEND_MESSAGE: 'FEED_WS_SEND_MESSAGE' = 'FEED_WS_SEND_MESSAGE';