export const ORDER_WS_DISCONNECT: 'ORDER_WS_DISCONNECT' = 'ORDER_WS_DISCONNECT';
export const ORDER_WS_CONNECT: 'ORDER_WS_CONNECT' = 'ORDER_WS_CONNECT';
export const ORDER_WS_CONNECTION_START: 'ORDER_WS_CONNECTION_START' = 'ORDER_WS_CONNECTION_START';
export const ORDER_WS_CONNECTION_SUCCESS: 'ORDER_WS_CONNECTION_SUCCESS' = 'ORDER_WS_CONNECTION_SUCCESS';
export const ORDER_WS_CONNECTION_ERROR: 'ORDER_WS_CONNECTION_ERROR' = 'ORDER_WS_CONNECTION_ERROR';
export const ORDER_WS_CONNECTION_CLOSED: 'ORDER_WS_CONNECTION_CLOSED' = 'ORDER_WS_CONNECTION_CLOSED';
export const ORDER_WS_GET_MESSAGE: 'ORDER_WS_GET_MESSAGE' = 'ORDER_WS_GET_MESSAGE';
export const ORDER_WS_SEND_MESSAGE: 'ORDER_WS_SEND_MESSAGE' = 'ORDER_WS_SEND_MESSAGE';